### ISSUE TITLE
Animated map - keeping data in the map

### ISSUE THREAD

**Issue by jpvillanuevac** [Robinlovelace/geocompr#561] opened 2020-07-11 09:05 UTC
First, thank you for this book. It is a fantastic resource.

I have a question/suggestion regarding [animated maps](https://geocompr.robinlovelace.net/adv-map.html#animated-maps) 

Imagine I have lat/long for new cases of disease Z detected in cityX on different dates.  If I want to create an animated map that shows the location of these cases in cityX, I can use the following code:

```
cases_diseaseZ = tm_shape(cityX) + tm_polygons() + 
  tm_shape(cases) + tm_dots(col="red") +
  tm_facets(along = "date", free.coords = FALSE)
```
and then use tm_animation. 

The code works well. However, when the gif map is showing cases detected on date t, the gif does not show the cases detected before that date.

I would like that my animated map keeps all the cases as the dates progress.
For example, if the gif is showing the cases found on date t, I would like that cases found on date t-1, date t-2, etc., stay on the map.

How can I do this with tmap? - If there is a way, would be worth to add this to the book?

Thank you

JP

**Comment by Robinlovelace** [comment] 2020-07-13 08:32
Hi @jpvillanuevac thanks for the question but it seems more like a general question about the `tmap` package rather than a question about the contents of or suggestions for the book (although I note your suggestion to add more examples of animated maps) so closing for now.

Can you provide a reproducible example? Because this is more a question about how you use the package than an issue with the package I suggest the best place to ask this could be in a user forum such as https://stackoverflow.com/ or https://community.rstudio.com/ . If you have identified an issue with the `tmap` package or would like to request a new feature you could ask at https://github.com/mtennekes/tmap/issues/. However, I suggest you only open issues if you have a reproducible example and a clearly defined issue (e.g. when I enter this command after running the previous lines of code I expect this to happen), which does not seem to be the case.

I'm glad you're finding the book of use/interest and welcome any further comments/suggestions on how to improve it.

**Closed by Robinlovelace** 2020-07-13 08:32 UTC
