### ISSUE TITLE
Ch. 9 - faceting example doesn't work

### ISSUE THREAD

**Issue by angoodkind** [Robinlovelace/geocompr#715] opened 2021-12-31 15:33 UTC
When running

```
tm_shape(world) +
  tm_polygons() +
  tm_shape(urb_1970_2030) +
  tm_symbols(col = "black", border.col = "white", size = "population_millions") +
  tm_facets(by = "year", nrow = 2, free.coords = FALSE)
```

I get the error:

```
Error in CPL_transform(x, crs, aoi, pipeline, reverse, desired_accuracy,  : 
  OGRCreateCoordinateTransformation(): transformation not available
In addition: Warning message:
In CPL_transform(x, crs, aoi, pipeline, reverse, desired_accuracy,  :
  GDAL Error 1: No PROJ.4 translation for destination SRS, coordinate transformation initialization has failed.
```

**Comment by Robinlovelace** [comment] 2021-12-31 22:01
Hi @angoodkind thanks for opening the issue. I'm going to close it for now because the issue you are seeing is not related to the book's content but to the versions of the software you have on your computer.

See full reproducible example below to show that it *can* be reproduced on up-to-date software:

``` r
library(spData)
library(tmap)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

urb_1970_2030 = urban_agglomerations %>% 
  filter(year %in% c(1970, 1990, 2010, 2030))

tm_shape(world) +
  tm_polygons() +
  tm_shape(urb_1970_2030) +
  tm_symbols(col = "black", border.col = "white", size = "population_millions") +
  tm_facets(by = "year", nrow = 2, free.coords = FALSE)
```

![](https://i.imgur.com/4ewF1np.png)

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Ubuntu 20.04.3 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language en_GB:en
#>  collate  en_GB.UTF-8
#>  ctype    en_GB.UTF-8
#>  tz       Europe/London
#>  date     2021-12-31
#>  pandoc   2.16.2 @ /usr/lib/rstudio/bin/quarto/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version  date (UTC) lib source
#>  abind          1.4-5    2016-07-21 [2] CRAN (R 4.0.2)
#>  assertthat     0.2.1    2019-03-21 [3] CRAN (R 4.0.0)
#>  backports      1.4.1    2021-12-13 [2] CRAN (R 4.1.2)
#>  base64enc      0.1-3    2015-07-28 [2] CRAN (R 4.0.2)
#>  cachem         1.0.6    2021-08-19 [2] CRAN (R 4.1.1)
#>  callr          3.7.0    2021-04-20 [3] CRAN (R 4.0.5)
#>  class          7.3-19   2021-05-03 [4] CRAN (R 4.0.5)
#>  classInt       0.4-3    2020-04-07 [2] CRAN (R 4.0.2)
#>  cli            3.1.0    2021-10-27 [2] CRAN (R 4.1.1)
#>  codetools      0.2-18   2020-11-04 [4] CRAN (R 4.0.3)
#>  crayon         1.4.2    2021-10-29 [2] CRAN (R 4.1.1)
#>  crosstalk      1.2.0    2021-11-04 [2] CRAN (R 4.1.2)
#>  DBI            1.1.1    2021-01-15 [2] CRAN (R 4.0.3)
#>  desc           1.4.0    2021-09-28 [2] CRAN (R 4.1.1)
#>  devtools       2.4.3    2021-11-30 [2] CRAN (R 4.1.2)
#>  dichromat      2.0-0    2013-01-24 [2] CRAN (R 4.0.2)
#>  digest         0.6.29   2021-12-01 [2] CRAN (R 4.1.2)
#>  dplyr        * 1.0.7    2021-06-18 [2] CRAN (R 4.1.1)
#>  e1071          1.7-9    2021-09-16 [2] CRAN (R 4.1.1)
#>  ellipsis       0.3.2    2021-04-29 [2] CRAN (R 4.1.1)
#>  evaluate       0.14     2019-05-28 [3] CRAN (R 4.0.0)
#>  fansi          0.5.0    2021-05-25 [2] CRAN (R 4.1.1)
#>  fastmap        1.1.0    2021-01-25 [2] CRAN (R 4.1.1)
#>  fs             1.5.2    2021-12-08 [2] CRAN (R 4.1.2)
#>  generics       0.1.1    2021-10-25 [2] CRAN (R 4.1.1)
#>  glue           1.6.0    2021-12-17 [1] CRAN (R 4.1.2)
#>  highr          0.9      2021-04-16 [3] CRAN (R 4.0.5)
#>  htmltools      0.5.2    2021-08-25 [2] CRAN (R 4.1.1)
#>  htmlwidgets    1.5.4    2021-09-08 [2] CRAN (R 4.1.1)
#>  KernSmooth     2.23-20  2021-05-03 [4] CRAN (R 4.0.5)
#>  knitr          1.37     2021-12-16 [1] CRAN (R 4.1.2)
#>  lattice        0.20-45  2021-09-22 [2] CRAN (R 4.1.1)
#>  leafem         0.1.6    2021-05-24 [2] CRAN (R 4.0.4)
#>  leaflet        2.0.4.1  2021-01-07 [2] CRAN (R 4.0.3)
#>  leafsync       0.1.0    2019-03-05 [2] CRAN (R 4.0.2)
#>  lifecycle      1.0.1    2021-09-24 [2] CRAN (R 4.1.1)
#>  lwgeom         0.2-8    2021-10-06 [2] CRAN (R 4.1.1)
#>  magrittr       2.0.1    2020-11-17 [2] CRAN (R 4.1.1)
#>  memoise        2.0.1    2021-11-26 [3] CRAN (R 4.1.2)
#>  pillar         1.6.4    2021-10-18 [2] CRAN (R 4.1.1)
#>  pkgbuild       1.3.1    2021-12-20 [3] CRAN (R 4.1.2)
#>  pkgconfig      2.0.3    2019-09-22 [2] CRAN (R 4.1.1)
#>  pkgload        1.2.4    2021-11-30 [3] CRAN (R 4.1.2)
#>  png            0.1-7    2013-12-03 [2] CRAN (R 4.0.2)
#>  prettyunits    1.1.1    2020-01-24 [3] CRAN (R 4.0.0)
#>  processx       3.5.2    2021-04-30 [2] CRAN (R 4.1.1)
#>  proxy          0.4-26   2021-06-07 [2] CRAN (R 4.0.4)
#>  ps             1.6.0    2021-02-28 [2] CRAN (R 4.1.1)
#>  purrr          0.3.4    2020-04-17 [2] CRAN (R 4.1.1)
#>  R.cache        0.15.0   2021-04-30 [2] CRAN (R 4.1.0)
#>  R.methodsS3    1.8.1    2020-08-26 [2] CRAN (R 4.1.0)
#>  R.oo           1.24.0   2020-08-26 [2] CRAN (R 4.1.0)
#>  R.utils        2.11.0   2021-09-26 [2] CRAN (R 4.1.1)
#>  R6             2.5.1    2021-08-19 [2] CRAN (R 4.1.1)
#>  raster         3.5-9    2021-12-10 [2] CRAN (R 4.1.2)
#>  RColorBrewer   1.1-2    2014-12-07 [2] CRAN (R 4.1.1)
#>  Rcpp           1.0.7    2021-07-07 [2] CRAN (R 4.1.1)
#>  remotes        2.4.2    2021-11-30 [1] CRAN (R 4.1.2)
#>  reprex         2.0.1    2021-08-05 [1] CRAN (R 4.1.2)
#>  rlang          0.4.12   2021-10-18 [2] CRAN (R 4.1.1)
#>  rmarkdown      2.11     2021-09-14 [2] CRAN (R 4.1.1)
#>  rprojroot      2.0.2    2020-11-15 [3] CRAN (R 4.0.3)
#>  s2             1.0.7    2021-09-28 [2] CRAN (R 4.1.1)
#>  sessioninfo    1.2.2    2021-12-06 [1] CRAN (R 4.1.2)
#>  sf             1.0-5    2021-12-17 [1] CRAN (R 4.1.2)
#>  sp             1.4-6    2021-11-14 [2] CRAN (R 4.1.2)
#>  spData       * 2.0.1    2021-09-21 [2] Github (nowosad/spData@9c942ba)
#>  spDataLarge    2.0.3    2021-12-17 [1] Github (nowosad/spDataLarge@d1ef6d4)
#>  stars          0.5-5    2021-12-17 [1] Github (r-spatial/stars@f045684)
#>  stringi        1.7.6    2021-11-29 [2] CRAN (R 4.1.2)
#>  stringr        1.4.0    2019-02-10 [2] CRAN (R 4.1.1)
#>  styler         1.6.2    2021-09-23 [2] CRAN (R 4.1.1)
#>  terra          1.5-3    2021-12-17 [1] Github (rspatial/terra@d69e6c9)
#>  testthat       3.1.1    2021-12-03 [3] CRAN (R 4.1.2)
#>  tibble         3.1.6    2021-11-07 [2] CRAN (R 4.1.2)
#>  tidyselect     1.1.1    2021-04-30 [2] CRAN (R 4.1.1)
#>  tmap         * 3.3-3    2021-12-17 [1] Github (mtennekes/tmap@1204aaa)
#>  tmaptools      3.1-1    2021-01-19 [2] CRAN (R 4.0.3)
#>  units          0.7-2    2021-06-08 [2] CRAN (R 4.0.4)
#>  usethis        2.1.5    2021-12-09 [1] CRAN (R 4.1.2)
#>  utf8           1.2.2    2021-07-24 [2] CRAN (R 4.1.0)
#>  vctrs          0.3.8    2021-04-29 [2] CRAN (R 4.1.1)
#>  viridisLite    0.4.0    2021-04-13 [2] CRAN (R 4.0.4)
#>  withr          2.4.3    2021-11-30 [2] CRAN (R 4.1.2)
#>  wk             0.5.0    2021-07-13 [2] CRAN (R 4.1.0)
#>  xfun           0.29     2021-12-14 [1] CRAN (R 4.1.2)
#>  XML            3.99-0.8 2021-09-17 [2] CRAN (R 4.1.1)
#>  yaml           2.2.1    2020-02-01 [2] CRAN (R 4.1.1)
#> 
#>  [1] /home/robin/R/x86_64-pc-linux-gnu-library/4.1
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

<sup>Created on 2021-12-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Robinlovelace** [comment] 2021-12-31 22:04
Please try updating R and R packages to the latest versions as described here: https://geocompr.robinlovelace.net/ in the chunk with lots of `remotes::install_github()` calls.

Does that help? I'm interested to learn what your session info is so try pasting the output of `devtools::session_info()` below.

Closing for now in any case.

**Closed by Robinlovelace** 2021-12-31 22:04 UTC

**Comment by angoodkind** [comment] 2022-01-01 00:46
Oops! I have no idea why I was still on R version 3.6. Upgraded to 4.1.2 and it works fine.
