### ISSUE TITLE
No content in 'Making maps with R' chapter

### ISSUE THREAD

**Issue by Camil88** [Robinlovelace/geocompr#587] opened 2020-11-11 17:40 UTC
Good morning, 

there's no content available in chapter 8 (in web version of the book: https://geocompr.robinlovelace.net/adv-map.html). I open this chapter and the only thing I can see on the page is 'References' (in every subchapters so from 8.1 to 8.7 is the same, no content at all). Other chapters of the book work very well besides this one.

**Comment by Robinlovelace** [comment] 2020-11-11 18:56
Are you sure? It works fine on Firefox for me: https://geocompr.robinlovelace.net/adv-map.html

Suggest trying again on different browsers to see if that fixes things.

**Comment by Robinlovelace** [comment] 2020-11-11 18:59
Reproducible example to show it's working - closing for now.

``` r
webshot::webshot("https://geocompr.robinlovelace.net/adv-map.html", file = "adv.png")
```

![](https://i.imgur.com/6RvwVXj.png)

``` r
magick::image_read("adv.png")
```

<img src="https://i.imgur.com/nuaM833.png" width="992" />

<sup>Created on 2020-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment] 2020-11-11 19:01
Reopening because I think I know the cause: non https elements in there.

![image](https://user-images.githubusercontent.com/1825120/98852916-4f383780-2450-11eb-95c6-4e28b2e1ce8e.png)

I think we should identify the source of that 'mixed content' and fix, then we can close this.

**Comment by Robinlovelace** [comment] 2020-11-11 20:26
The `linkchecker` program found the following issues:

```
URL        `../images/caution.png'
Parent URL https://geocompr.robinlovelace.net/css/style.css, line 7, col 24
Real URL   https://geocompr.robinlovelace.net/images/caution.png
Check time 1.346 seconds
Result     Error: 404 Not Found

URL        `../images/important.png'
Parent URL https://geocompr.robinlovelace.net/css/style.css, line 10, col 24
Real URL   https://geocompr.robinlovelace.net/images/important.png
Check time 1.089 seconds
Result     Error: 404 Not Found

URL        `../images/tip.png'
Parent URL https://geocompr.robinlovelace.net/css/style.css, line 16, col 24
Real URL   https://geocompr.robinlovelace.net/images/tip.png
Check time 1.098 seconds
Result     Error: 404 Not Found
10 threads active,    81 links queued,  390 links in 481 URLs checked, runtime 46 seconds

URL        `../images/warning.png'
Parent URL https://geocompr.robinlovelace.net/css/style.css, line 19, col 24
Real URL   https://geocompr.robinlovelace.net/images/warning.png
Check time 1.107 seconds
Result     Error: 404 Not Found

URL        `www.qgis.org'
Name       `QGIS'
Parent URL https://geocompr.robinlovelace.net/intro.html, line 577, col 57
Real URL   https://geocompr.robinlovelace.net/www.qgis.org
Check time 1.395 seconds
Result     Error: 404 Not Found

URL        `www.saga-gis.org'
Name       `SAGA'
Parent URL https://geocompr.robinlovelace.net/intro.html, line 577, col 139
Real URL   https://geocompr.robinlovelace.net/www.saga-gis.org
Check time 1.237 seconds
Result     Error: 404 Not Found
```

**Comment by Robinlovelace** [comment] 2020-11-11 21:40
Think I've found the cause of the issue: https://geocompr.github.io/img/leaflet.html

**Closed** 2020-11-11 21:57 UTC

**Comment by Camil88** [comment] 2020-11-12 10:34
Ok, thanks, it's working on Firefox. Still doesn't work on Edge but it's not a problem now, I'll change the browser;) Just wanted you to know that this chapter is not working on each browser, which is strange. Anyway, thanks for a solution:)
