### ISSUE TITLE
Error running example in rstudio

### ISSUE THREAD

**Issue by alankjackson** [Robinlovelace/geocompr#847] opened 2022-08-18 04:10 UTC
The example in https://geocompr.robinlovelace.net/spatial-class.html

```
plot(world["pop"], reset = FALSE)
plot(asia, add = TRUE, col = "red")
```
fails in rstudio. To fix it, write it as:
```
{
plot(world["pop"], reset = FALSE)
plot(asia, add = TRUE, col = "red")
}
```

**Comment by Robinlovelace** [comment] 2022-08-18 04:48
I'm not sure the cause of your issue but it works fine on my computer as shown below.

![image](https://user-images.githubusercontent.com/1825120/185296004-589243ad-1725-4b29-9051-2beb8e778a3c.png)

Is it an issue with your RStudio installation, or maybe how you're running the code. When reporting issues it helps to also report the error message you're seeing. Not sure what's going on here but confident that it's not the book content at fault so closing for now.

Thanks for the feedback in any case and keep us posted if you find out the underlying cause.

**Closed by Robinlovelace** 2022-08-18 04:48 UTC
