### ISSUE TITLE
Failing to compile the book at chapter 5

### ISSUE THREAD

**Issue by talgalili** [Robinlovelace/geocompr#365] opened 2019-02-03 23:33 UTC
(After installing the dependancies)
I'm running 
```
bookdown::render_book("index.Rmd") # to build the book
```
And get:
```

  |......................................                           |  58%
label: 05-geometry-operations-44
Quitting from lines 789-790 (05-geometry-operations.Rmd) 
Error in methods::validObject(y) : invalid class "Extent" object: TRUE
Calls: local ... eval -> eval -> crop -> crop -> .local -> <Anonymous>
In addition: Warning messages:
1: package 'sf' was built under R version 3.4.4 
2: package 'sp' was built under R version 3.4.4 
3: package 'dplyr' was built under R version 3.4.4 
4: package 'spData' was built under R version 3.4.4 
5: package 'tmap' was built under R version 3.4.4 
6: package 'bindrcpp' was built under R version 3.4.4 

Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 05-geometry-operations.Rmd
```

Note:
```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.3   bookdown_0.9     htmltools_0.3.6  tools_3.4.3      rstudioapi_0.9.0
 [6] yaml_2.2.0       Rcpp_1.0.0       rmarkdown_1.11   knitr_1.20       xfun_0.4        
[11] digest_0.6.18    evaluate_0.12   
```

**Comment by Robinlovelace** [comment] 2019-02-04 08:00
Hi @talgalili thanks for raising the issue, glad you're trying it out! I cannot reproduce the issue. Have you tried installing the latest versions of packages used in this book?

You can do this with:

```r
remotes::install_github("robinlovelace/geocompkg")
```

**Comment by talgalili** [comment] 2019-02-04 17:53
I ran:
```
remotes::install_github("geocompr/geocompkg")
```

And then when running:
`bookdown::render_book("index.Rmd") # to build the boo`


I still get when getting to the fifth file:


```

  |......................................                           |  58%
label: 05-geometry-operations-44
Quitting from lines 789-790 (05-geometry-operations.Rmd) 
Error in methods::validObject(y) : invalid class "Extent" object: TRUE
Calls: local ... eval -> eval -> crop -> crop -> .local -> <Anonymous>
In addition: Warning messages:
1: package 'sf' was built under R version 3.4.4 
2: package 'sp' was built under R version 3.4.4 
3: package 'dplyr' was built under R version 3.4.4 
4: package 'spData' was built under R version 3.4.4 
5: package 'tmap' was built under R version 3.4.4 
6: package 'bindrcpp' was built under R version 3.4.4 

Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 05-geometry-operations.Rmd
> 
```

**Comment by Robinlovelace** [comment] 2019-02-05 12:04
I would try updating to packages built under the latest version of R (`3.5.2`).

**Comment by Robinlovelace** [comment] 2019-03-14 14:47
Closing for now as not reproducible. Did you get to the bottom of this @talgalili ?

**Closed by Robinlovelace** 2019-03-14 14:47 UTC

**Comment by mrska** [comment] 2019-04-19 08:24
I got exactly the same error (line 771)
`crop(srtm, zion)`
Result:
`Error in methods::validObject(y) : invalid class "Extent" object: TRUE`
`
sf: 0.7-3; 
raster: 2.8-19`

**Comment by Nowosad** [comment] 2019-04-19 08:34
Can you install the github version of the raster package and try again?
Btw what is your spDataLarge package version?

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.3.2, PROJ 4.9.3
library(raster)
#> Loading required package: sp
library(spDataLarge)

srtm = raster(system.file("raster/srtm.tif", package = "spDataLarge"))
zion = st_read(system.file("vector/zion.gpkg", package = "spDataLarge"))
#> Reading layer `zion' from data source `/home/jn/R/x86_64-redhat-linux-gnu-library/3.5/spDataLarge/vector/zion.gpkg' using driver `GPKG'
#> Simple feature collection with 1 feature and 11 fields
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: 302903.1 ymin: 4112244 xmax: 334735.5 ymax: 4153087
#> epsg (SRID):    NA
#> proj4string:    +proj=utm +zone=12 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
zion = st_transform(zion, projection(srtm))

srtm_cropped = crop(srtm, zion)
srtm_cropped
#> class      : RasterLayer 
#> dimensions : 436, 438, 190968  (nrow, ncol, ncell)
#> resolution : 0.0008333333, 0.0008333333  (x, y)
#> extent     : -113.2279, -112.8629, 37.14125, 37.50458  (xmin, xmax, ymin, ymax)
#> crs        : +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
#> source     : memory
#> names      : srtm 
#> values     : 1049, 2875  (min, max)
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
<details><summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                          
#>  version  R version 3.5.3 (2019-03-11)   
#>  os       Fedora 29 (Workstation Edition)
#>  system   x86_64, linux-gnu              
#>  ui       X11                            
#>  language (EN)                           
#>  collate  en_US.UTF-8                    
#>  ctype    en_US.UTF-8                    
#>  tz       Europe/Warsaw                  
#>  date     2019-04-19                     
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source                          
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.2)                  
#>  backports     1.1.3   2018-12-14 [1] CRAN (R 3.5.2)                  
#>  callr         3.2.0   2019-03-15 [1] CRAN (R 3.5.2)                  
#>  class         7.3-15  2019-01-01 [2] CRAN (R 3.5.3)                  
#>  classInt      0.3-1   2018-12-18 [1] CRAN (R 3.5.2)                  
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.2)                  
#>  codetools     0.2-16  2018-12-24 [2] CRAN (R 3.5.3)                  
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)                  
#>  DBI           1.0.0   2018-05-02 [1] CRAN (R 3.5.2)                  
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.2)                  
#>  devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.2)                  
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.2)                  
#>  e1071         1.7-1   2019-03-19 [1] CRAN (R 3.5.2)                  
#>  evaluate      0.13    2019-02-12 [1] CRAN (R 3.5.2)                  
#>  fs            1.2.7   2019-03-19 [1] CRAN (R 3.5.2)                  
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.5.2)                  
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.5.2)                  
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.2)                  
#>  knitr         1.22    2019-03-08 [1] CRAN (R 3.5.2)                  
#>  lattice       0.20-38 2018-11-04 [2] CRAN (R 3.5.3)                  
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.2)                  
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.2)                  
#>  pkgbuild      1.0.3   2019-03-20 [1] CRAN (R 3.5.2)                  
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.2)                  
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.2)                  
#>  processx      3.3.0   2019-03-10 [1] CRAN (R 3.5.2)                  
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.2)                  
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.2)                  
#>  raster      * 2.9-2   2019-04-12 [1] Github (rspatial/raster@81060dc)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.5.2)                  
#>  remotes       2.0.4   2019-04-10 [1] CRAN (R 3.5.3)                  
#>  rgdal         1.4-3   2019-03-14 [1] CRAN (R 3.5.2)                  
#>  rlang         0.3.4   2019-04-07 [1] CRAN (R 3.5.3)                  
#>  rmarkdown     1.12    2019-03-14 [1] CRAN (R 3.5.2)                  
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.2)                  
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)                  
#>  sf          * 0.7-3   2019-02-21 [1] CRAN (R 3.5.2)                  
#>  sp          * 1.3-1   2018-06-05 [1] CRAN (R 3.5.2)                  
#>  spDataLarge * 0.3.1   2019-04-05 [1] local                           
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.5.2)                  
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.2)                  
#>  testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.2)                  
#>  units         0.6-2   2018-12-05 [1] CRAN (R 3.5.2)                  
#>  usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.2)                  
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)                  
#>  xfun          0.5     2019-02-20 [1] CRAN (R 3.5.2)                  
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.2)                  
#> 
#> [1] /home/jn/R/x86_64-redhat-linux-gnu-library/3.5
#> [2] /usr/lib64/R/library
#> [3] /usr/share/R/library
```

</details>
