### ISSUE TITLE
Chapter 4 Exercise 1 - Bonus question incomplete

### ISSUE THREAD

**Issue by Lvulis** [Robinlovelace/geocompr#810] opened 2022-06-20 19:56 UTC
In the [first exercise of chapter 4](https://geocompr.robinlovelace.net/spatial-operations.html#exercises-2) the bonus question states 
```
Bonus: plot the result using the [plot()](https://r-spatial.github.io/sf/reference/plot.html) function to show all of New Zealand, canterbury region highlighted in yellow, high points in Canterbury represented with black dots and
```

**Comment by Nowosad** [comment] 2022-06-25 01:37
@Lvulis -- thanks for letting us know about the issue.

@Robinlovelace  -- it was introduced here -- https://github.com/Robinlovelace/geocompr/commit/a28def32681fc13ff202bd7525bcded20ac9213e. Can you try to fix it?

**Comment by Robinlovelace** [comment] 2022-06-25 12:34
Good spot @Lvulis and yes that looks like the cause Jakub. The below is definitely not right. On the case!

**Comment by Robinlovelace** [comment] 2022-06-25 12:35
![image](https://user-images.githubusercontent.com/1825120/175773734-300146f1-8d89-439d-9c44-7f35a9eb7cc4.png)

**Comment by Robinlovelace** [comment] 2022-06-25 13:03
This was fixed in the changes represented in the link above. Let us know @Lvulis if this works for you. Any further feedback v. welcome!

**Closed** 2022-06-25 13:02 UTC

**Comment by Lvulis** [comment] 2022-06-25 14:55
Thank you @Robinlovelace and @Nowosad. I'm enjoying new version of the book, great work!
