### ISSUE TITLE
Unable to reproduce Figure 8.13 - issue with st_transform?

### ISSUE THREAD

**Issue by dhersz** [Robinlovelace/geocompr#531] opened 2020-04-28 20:37 UTC
I got an error while tried to reproduce [Figure 8.13](https://geocompr.robinlovelace.net/adv-map.html#fig:urban-facet):

```R
urb_1970_2030 = urban_agglomerations %>% 
    filter(year %in% c(1970, 1990, 2010, 2030))

tm_shape(world) +
    tm_polygons() +
    tm_shape(urb_1970_2030) +
    tm_symbols(col = "black", border.col = "white", size = "population_millions") +
    tm_facets(by = "year", nrow = 2, free.coords = FALSE)
#> Warning in CPL_transform(x, crs, aoi, pipeline, reverse): GDAL Error 1: No PROJ.
#> 4 translation for source SRS, coordinate transformation initialization has
#> failed.
#> Error in CPL_transform(x, crs, aoi, pipeline, reverse): OGRCreateCoordinateTransformation() returned NULL: PROJ available?
```

The error message lead me to believe it was something to do with the proj4string element, so I checked it out.

```R
st_crs(world)$proj4string
#> [1] "+proj=longlat +datum=WGS84 +no_defs "

st_crs(urb_1970_2030)$proj4string
#> [1] ""
```

I tried to reproject `urb_1970_2030` to see if it would fix the issue, but apparently that's exactly the problem.

```R
st_transform(urb_1970_2030, crs = "+proj=longlat +datum=WGS84 +no_defs ")
#> Warning in CPL_transform(x, crs, aoi, pipeline, reverse): GDAL Error 1: No PROJ.
#> 4 translation for source SRS, coordinate transformation initialization has
#> failed.
#> Error in CPL_transform(x, crs, aoi, pipeline, reverse): OGRCreateCoordinateTransformation() returned NULL: PROJ available?
```

**Comment by Nowosad** [comment] 2020-04-29 09:33
I cannot reproduce this issue. I think the problem is with either outdated versions of your packages or outdated versions of your system libraries.

1. Try `remotes::install_github("geocompr/geocompkg")`, restart R session and try the code again
2. What is your operating system and GDAL and PROJ versions?

**Comment by dhersz** [comment] 2020-04-29 15:15
I still get the same error after reinstalling the packages.

Operating system, GDAL and PROJ infos:

```R
library(sf)
#> Warning: package 'sf' was built under R version 3.6.3
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3

Sys.info()
#>           sysname           release           version          nodename 
#>         "Windows"          "10 x64"     "build 18363" "DESKTOP-PCVEI3N" 
#>           machine             login              user    effective_user 
#>          "x86-64"         "Usuario"         "Usuario"         "Usuario"
```

**Comment by Robinlovelace** [comment] 2020-04-29 15:16
Heads-up, my colleague @mem48 was having similar issues on Windows. If you find a solution please let us know.

**Comment by Robinlovelace** [comment] 2020-05-02 20:39
As mentioned in https://github.com/r-spatial/sf/issues/1386 the following line of code should fix the issue. Let us know if it does @dhersz:

```r
st_crs(urb_1970_2030) = 4326
```

**Comment by Robinlovelace** [comment] 2020-05-03 13:22
Closing because I think it's a duplicate of https://github.com/Robinlovelace/geocompr/issues/508

Let us know how you get on @dhersz, happy for this to be re-opened if you think it's an issue with the book and not an issue with set-up that should be solved in future releases of `sf`.

**Closed by Robinlovelace** 2020-05-03 13:22 UTC
