### ISSUE TITLE
Issue with rendering book locally

### ISSUE THREAD

**Issue by erstearns** [Robinlovelace/geocompr#268] opened 2018-08-07 21:49 UTC
Hello there! I am trying to run the code at the very start of the book to render it locally while using Windows 10: 

`bookdown::render_book("index.Rmd") # to build the book`

I get the following error messages:

```
`Quitting from lines 398-400 (04-spatial-operations.Rmd) 
Error in tm_format("World") : could not find function "tm_format"
Calls: local ... eval -> eval -> source -> withVisible -> eval -> eval

Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 04-spatial-operations.Rmd
````

I read that `tm_format()` has replaced deprecated **tmap** functions, so is it possible the tmap package loaded with `devtools::install_github("robinlovelace/geocompr")` is an older version of **tmap** than is needed to run the function` tm_format`?

I have loaded **tmap**, then run `?tm_format` and get the `No documentation for ‘tm_format’ in specified packages and libraries: you could try ‘??tm_format’` message. I tried manually installing the newest version of **tmap**, however this resulted in dependencies being re-loaded and updated, including **tmaptools**, which overwrote **tmap** functions and locked the tmap library from use.

Any ideas on how to fix this? Thank you in advance!

**Comment by Robinlovelace** [comment] 2018-08-07 22:20
Thanks for raising the issue. I'm not sure what the problem is but think it's the spatial join example. Something is clearly up from the output below because the figure is different from this one in the book: http://geocompr.robinlovelace.net/spatial-operations.html#fig:spatial-join

Try running the following commands, from `file.edit("code/04-spatial-join.R")` in the book repo (running the `session_info()` bit will shed light on what version of **tmap** you're using, I've currently got `2.0-1`):

``` r
# Aim: demonstrate spatial joins ------------------------------------------
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.2, proj.4 4.9.2
library(spData)
library(tmap)
# names(world)
# names(urban_agglomerations)
# Question arising from the data:
# what % of country populations lived in their largest agglomerations?
# explanation: we're joining the point data onto world

if(!exists("random_joined")) {
  set.seed(2018)
  bb_world = st_bbox(world)
  random_df = tibble::tibble(
    x = runif(n = 10, min = bb_world[1], max = bb_world[3]),
    y = runif(n = 10, min = bb_world[2], max = bb_world[4])
  )
  random_points = st_as_sf(random_df, coords = c("x", "y")) %>% 
    st_set_crs(4326)
  
  world_random = world[random_points, ]
  random_joined = st_join(random_points, world["name_long"])
  
}
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar

jm0 = tm_shape(world) + tm_borders(lwd = 0.2) + tm_format("World")

jm1 = jm0 +
  tm_shape(shp = random_points, bbox = bb_world) + tm_symbols(col = "black", shape = 4, border.lwd = 2) +
  tm_layout(scale = 1, legend.bg.color = "white", legend.bg.alpha = 0.3, legend.position = c("right", "bottom"))

jm2 = jm0 +
  tm_shape(world_random, bbox = bb_world) +
  tm_fill(col = "name_long", palette = "Dark2") +
  tm_layout(legend.show = FALSE)
  #tm_borders(col = "name_long", lwd = 4) + # issue with tmap: no variable border
  # tm_layout(scale = 1, legend.bg.color = "white", legend.bg.alpha = 0.3, legend.position = c("right", "bottom"))

jm3 = jm0 +
  tm_shape(shp = random_joined, bbox = bb_world) +
  tm_symbols(col = "name_long", shape = 4, border.lwd = 2, palette = "Dark2") +
  tm_layout(legend.show = FALSE)
# +
#   tm_layout(scale = 1, legend.bg.color = "white", legend.bg.alpha = 0.3, legend.position = c("right", "bottom"))

jm4 = jm0 +
  tm_shape(shp = random_joined, bbox = bb_world) +
  tm_symbols(col = "name_long", shape = 4, border.lwd = 2, palette = "Dark2") +
  tm_layout(legend.only = TRUE)

tmap_arrange(jm1, jm2, jm3, jm4, nrow = 2, ncol = 2)
#> Warning: Number of levels of the variable "name_long" is 177, which is
#> larger than max.categories (which is 30), so levels are combined. Set
#> tmap_options(max.categories = 177) in the layer function to show all
#> levels.

#> Warning: Number of levels of the variable "name_long" is 177, which is
#> larger than max.categories (which is 30), so levels are combined. Set
#> tmap_options(max.categories = 177) in the layer function to show all
#> levels.

#> Warning: Number of levels of the variable "name_long" is 177, which is
#> larger than max.categories (which is 30), so levels are combined. Set
#> tmap_options(max.categories = 177) in the layer function to show all
#> levels.
```

![](https://i.imgur.com/ivmiq3W.png)

Created on 2018-08-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_GB:en                    
#>  collate  en_GB.UTF-8                 
#>  tz       Europe/London               
#>  date     2018-08-07
#> Packages -----------------------------------------------------------------
#>  package      * version    date       source                              
#>  backports      1.1.2      2017-12-13 CRAN (R 3.5.0)                      
#>  base         * 3.5.1      2018-07-03 local                               
#>  base64enc      0.1-3      2015-07-28 CRAN (R 3.5.0)                      
#>  class          7.3-14     2015-08-30 cran (@7.3-14)                      
#>  classInt       0.2-3      2018-04-16 cran (@0.2-3)                       
#>  codetools      0.2-15     2016-10-05 CRAN (R 3.5.0)                      
#>  colorspace     1.3-2      2016-12-14 CRAN (R 3.5.0)                      
#>  compiler       3.5.1      2018-07-03 local                               
#>  crayon         1.3.4      2017-09-16 CRAN (R 3.5.0)                      
#>  crosstalk      1.0.0      2016-12-21 cran (@1.0.0)                       
#>  curl           3.2        2018-03-28 CRAN (R 3.5.0)                      
#>  datasets     * 3.5.1      2018-07-03 local                               
#>  DBI            1.0.0      2018-05-02 CRAN (R 3.5.0)                      
#>  devtools       1.13.6     2018-06-27 CRAN (R 3.5.1)                      
#>  dichromat      2.0-0      2013-01-24 CRAN (R 3.1.1)                      
#>  digest         0.6.15     2018-01-28 CRAN (R 3.5.0)                      
#>  e1071          1.6-8      2017-02-02 cran (@1.6-8)                       
#>  evaluate       0.11       2018-07-17 CRAN (R 3.5.1)                      
#>  foreach        1.4.4      2017-12-12 cran (@1.4.4)                       
#>  gdalUtils      2.0.1.14   2018-04-23 cran (@2.0.1.1)                     
#>  graphics     * 3.5.1      2018-07-03 local                               
#>  grDevices    * 3.5.1      2018-07-03 local                               
#>  grid           3.5.1      2018-07-03 local                               
#>  htmltools      0.3.6.9001 2018-06-17 Github (rstudio/htmltools@3aee819)  
#>  htmlwidgets    1.2        2018-04-19 cran (@1.2)                         
#>  httpuv         1.4.5      2018-07-19 CRAN (R 3.5.1)                      
#>  httr           1.3.1      2017-08-20 cran (@1.3.1)                       
#>  iterators      1.0.10     2018-07-13 CRAN (R 3.5.1)                      
#>  KernSmooth     2.23-15    2015-06-29 cran (@2.23-15)                     
#>  knitr          1.20       2018-02-20 CRAN (R 3.5.0)                      
#>  later          0.7.3      2018-06-08 CRAN (R 3.5.0)                      
#>  lattice        0.20-35    2017-03-25 CRAN (R 3.5.0)                      
#>  leaflet        2.0.1.9000 2018-07-22 Github (cmcaine/leaflet@012bec5)    
#>  lwgeom         0.1-4      2018-01-28 CRAN (R 3.5.0)                      
#>  magrittr       1.5        2014-11-22 CRAN (R 3.5.0)                      
#>  mapview        2.4.0      2018-04-28 cran (@2.4.0)                       
#>  memoise        1.1.0      2017-04-21 CRAN (R 3.5.0)                      
#>  methods      * 3.5.1      2018-07-03 local                               
#>  mime           0.5        2016-07-07 CRAN (R 3.5.0)                      
#>  munsell        0.5.0      2018-06-12 CRAN (R 3.5.0)                      
#>  pillar         1.3.0      2018-07-14 CRAN (R 3.5.1)                      
#>  plyr           1.8.4      2016-06-08 CRAN (R 3.5.0)                      
#>  png            0.1-7      2013-12-03 cran (@0.1-7)                       
#>  promises       1.0.1      2018-04-13 CRAN (R 3.5.0)                      
#>  R.methodsS3    1.7.1      2016-02-16 cran (@1.7.1)                       
#>  R.oo           1.22.0     2018-04-22 cran (@1.22.0)                      
#>  R.utils        2.6.0      2017-11-05 cran (@2.6.0)                       
#>  R6             2.2.2      2017-06-17 cran (@2.2.2)                       
#>  raster         2.6-7      2017-11-13 cran (@2.6-7)                       
#>  RColorBrewer   1.1-2      2014-12-07 CRAN (R 3.5.0)                      
#>  Rcpp           0.12.18    2018-07-23 cran (@0.12.18)                     
#>  rgdal          1.3-3      2018-06-22 cran (@1.3-3)                       
#>  rgeos          0.3-28     2018-06-08 cran (@0.3-28)                      
#>  rlang          0.2.1      2018-05-30 cran (@0.2.1)                       
#>  rmarkdown      1.10       2018-06-11 cran (@1.10)                        
#>  rprojroot      1.3-2      2018-01-03 CRAN (R 3.5.0)                      
#>  satellite      1.0.1      2017-10-18 cran (@1.0.1)                       
#>  scales         0.5.0      2017-08-24 CRAN (R 3.5.0)                      
#>  sf           * 0.6-4      2018-08-03 Github (r-spatial/sf@59ec93e)       
#>  shiny          1.1.0      2018-05-17 CRAN (R 3.5.0)                      
#>  sp             1.3-1      2018-06-05 CRAN (R 3.5.0)                      
#>  spData       * 0.2.9.3    2018-08-03 Github (nowosad/spData@4fc4935)     
#>  spDataLarge    0.2.7.1    2018-08-03 Github (nowosad/spDataLarge@b0ccecc)
#>  stats        * 3.5.1      2018-07-03 local                               
#>  stats4         3.5.1      2018-07-03 local                               
#>  stringi        1.2.4      2018-07-20 CRAN (R 3.5.1)                      
#>  stringr        1.3.1      2018-05-10 cran (@1.3.1)                       
#>  tibble         1.4.2      2018-01-22 CRAN (R 3.5.0)                      
#>  tmap         * 2.0-1      2018-08-03 Github (mtennekes/tmap@8177c5d)     
#>  tmaptools      2.0-1      2018-08-03 Github (mtennekes/tmaptools@1395296)
#>  tools          3.5.1      2018-07-03 local                               
#>  units          0.6-0      2018-06-09 cran (@0.6-0)                       
#>  utils        * 3.5.1      2018-07-03 local                               
#>  viridisLite    0.3.0      2018-02-01 CRAN (R 3.5.0)                      
#>  webshot        0.5.0      2017-11-29 CRAN (R 3.5.0)                      
#>  withr          2.1.2      2018-03-15 CRAN (R 3.5.0)                      
#>  XML            3.98-1.13  2018-08-01 cran (@3.98-1.)                     
#>  xml2           1.2.0      2018-01-24 CRAN (R 3.5.0)                      
#>  xtable         1.8-2      2016-02-05 CRAN (R 3.5.0)                      
#>  yaml           2.1.19     2018-05-01 CRAN (R 3.5.0)
```

</details>

**Comment by Robinlovelace** [comment] 2018-08-07 22:47
Update: the legend issue is fixed in https://github.com/Robinlovelace/geocompr/commit/cd60b32295f1f08d7417d50d2fbaf0dd4bd8cc4d

I cannot reproduce the issue with every version of **tmap** I've tried (just installed latest CRAN version). Are I suggest ensuring you've got the latest CRAN versions of all packages and the book and trying again - if you could identify the line of code that is failing on your computer that would also help resolve the issue.

**Comment by erstearns** [comment] 2018-08-08 18:41
Hi there,

Thank you for your quick reply, as always!

Ok, so when I printed `sessionInfo()`, I did find that my **tmap** package was not the latest (see below). 

![image](https://user-images.githubusercontent.com/25041596/43857279-b6d8d32c-9aff-11e8-938a-37995855bbbc.png)


It was breaking in 04-spatial-join.R, line 29:

![image](https://user-images.githubusercontent.com/25041596/43857290-be4f043c-9aff-11e8-8aa2-e377fd1d11f9.png)

Loading **tmap** directly from CRAN resolved the issue this time. I believe the tmap version included in `devtools::install_github("robinlovelace/geocompr")` is the older version however and if that could be updated, may prevent others from encountering this as well. Thank you, again, for your help!

**Comment by Robinlovelace** [comment] 2018-08-09 09:32
Glad it's fixed, thanks for the constructive feedback as always (more welcome, especially suggestions on how to improve the book).

```
devtools::install_github("robinlovelace/geocompr")
```

It should install the CRAN version of **tmap**, it's not a remote:  https://github.com/Robinlovelace/geocompr/blob/master/DESCRIPTION#L49

**Closed by Robinlovelace** 2018-08-09 09:32 UTC
