### ISSUE TITLE
Unable to render Chapter 8

### ISSUE THREAD

**Issue by jamietsakalos** [Robinlovelace/geocompr#468] opened 2020-01-22 23:30 UTC
(1) If it's about content link to the offending link/section

Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 08-mapping.Rmd

(2) If it's a about code, a reproducible example will help 

I have just set up a new computer with Open R and R studio and followed all instructions (https://bookdown.org/robinlovelace/geocompr/), however I run into an error when trying to render the book. I have also attempted on a different computer but to no avail.

(3) Any other comments/questions else welcome

Any advice / assistance would be greatly appreciated.

**Comment by Robinlovelace** [comment] 2020-01-23 07:46
Hi @jamietsakalos, I'm sorry you're having issues but will close this issue because you have not provided details on what the issue is, such as operating system, R version and what the error message was. If you provide those, in a reproducible example, I'd be happy to help. If you're running Ubuntu I recommend the install instructions here: https://rtask.thinkr.fr/installation-of-r-3-5-on-ubuntu-18-04-lts-and-tips-for-spatial-packages/

This section of the book may also help: https://geocompr.robinlovelace.net/spatial-class.html#prerequisites

Good luck!

**Closed by Robinlovelace** 2020-01-23 07:46 UTC
